name: Suggestion
description: Suggest an idea
title: "S"
labels: ["suggestion"]

body:
  - type: input
    id: title_input
    attributes:
      label: Title
    validations:
      required: true

  - type: textarea
    id: idea
    attributes:
      label: Idea
    validations:
      required: true

  - type: input
    id: repository
    attributes:
      label: Repository
    validations:
      required: true
