name: 💡 Suggestion
description: Suggest an idea or improvement
title: " "
labels: ["suggestion"]

body:
  - type: textarea
    id: idea
    attributes:
      label: Idea
    validations:
      required: true

  - type: dropdown
    id: repository
    attributes:
      label: Repository
      description: Select or type (copy from list below)
      options:
        - Copy & paste from list below
        - Other
    validations:
      required: true

  - type: textarea
    id: repo_input
    attributes:
      label: Repository Name
      description: Paste exact repository name here
      placeholder: All-Tasks
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📂 Your repositories (copy from here)
        All-Tasks  
        Chaos-Double-Pendulum-Simulator
